title: Welcome to Braintree Support
description:  Documentation, Support and Resources for Braintree's Trade Assistant Extension to Microsoft Dynamics 365 Business Central
theme: jekyll-theme-cayman
github:
  is_project_page: false